name: Github Auto PR Label,Approve and Merge

on: [pull_request]
jobs:
  AutoLabelandMerge:
    runs-on: ubuntu-latest
    env:
      #####set the PATH to scan File for changes  
      TGT_PATH: 'aws/approle'  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
 
               
      
      - name: Checkout head and base branch
        id: HeadandTarget
        run: |
          git fetch --no-tags  origin ${{ github.base_ref }}
          git fetch --no-tags  origin ${{ github.head_ref }}
          # get the actual source for two branches
          git checkout origin/${{ github.base_ref }}
          git checkout origin/${{ github.head_ref }}
          # get back to the merge commit
          git checkout ${{ github.sha }}
               
		  
												
		  
		  
      - name: Processing Files Changed in PR
        id: ConditionCheckStep
        run: |            
              CHANGED_FILES=$(git diff --name-only remotes/origin/${{ github.base_ref }}...remotes/origin/${{ github.head_ref }} )
              CHANGED_FILES_ARR=($CHANGED_FILES)
              #####checkpoint 1 : check right files are being fetched in diff
              #####echo $CHANGED_FILES

              for i in "${CHANGED_FILES_ARR[@]}"
                  do
                     #####Files modified should be of format  "$TGT_PATH/approle"*

                     if [[ !("$i" == "$TGT_PATH/approle"* )]]; then
                        echo "files changed are not supported for auto approval will exit" 
                        echo "::set-output name=comment::Unintended Files were changed"
                        exit 0               
                     fi

                  done

              #####Getting files info changed in PR 
              git diff --unified=0  remotes/origin/${{ github.base_ref }}...remotes/origin/${{ github.head_ref }} -- $TGT_PATH >File
              #####checkpoint 2: check to get only changed files under $TGT_PATH

              #####cat File   


              ##### removing base line with -- and getting remaing info 
              if grep -q -v '^\-\-' File; then
                  echo "removing diff header"
                  grep -v '^\-\-' File >FilterFile
              else
                  echo "files changed outside valid directory"
                  echo "::set-output name=comment::changes made at different location"
                  exit 0
              fi

              #####checkpoint 3 : Filter the lines containing changes 
              #####cat FilterFile
              if grep -q '^\-' FilterFile; then
                  echo "PR contains files with deleted or modified lines!!"
                  echo "::set-output name=comment::Lines were Deleted or Modified"
                  exit 0
              else
                  echo "PR safe for labeling and Auto approve!!"
                  echo "::set-output name=comment::Pass"
              fi

      - name: 'Comment On Unapproved PR'
        uses: actions/github-script@v3
        if: steps.ConditionCheckStep.outputs.comment != 'Pass'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |            
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Thank you for your contribution !📣 PR cannot be auto approved because ⚠️ ${{steps.ConditionCheckStep.outputs.comment}} ⚠️ ' });
      - name: 'Labeling PR'
        uses: actions/github-script@0.3.0
        if: steps.ConditionCheckStep.outputs.comment == 'Pass'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['auto-run']
            })
      - name: Approving PR 
        uses: hmarr/auto-approve-action@v2.0.0
        if: steps.ConditionCheckStep.outputs.comment == 'Pass'
        with:
         github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: 'Comment On Approved PR'
        uses: actions/github-script@v3
        if: steps.ConditionCheckStep.outputs.comment == 'Pass'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Thank you for your contribution ! 👋  Congratulation your PR has been approved and will be Merged automatically' });
      - name: merge
        uses: framer/merge-approved-pull-request-action@master
        if: steps.ConditionCheckStep.outputs.comment == 'True'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABEL: auto-run
