# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: label check
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        if: contains(github.event.pull_request.labels.*.name, 'auto-run')
        run: echo Add other actions to build,

            
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: label check
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        if: contains(github.event.pull_request.labels.*.name, 'auto-run')
        run: echo Add other actions to build
  test2:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: dependecy check.

    
