# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: check
on:
  label:
    types: [created, deleted]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - name: label check
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            if: contains(github.event.pull_request.labels.*.name, 'frontend')
            run: echo "testing frontend" 
        with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
