name: checkout

on: [pull_request]
jobs:
  AutoLabelandMerge:
    runs-on: ubuntu-latest
    env:
      TGT_PATH: 'aws/approle'  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: commands  
        run: |
          git fetch --no-tags origin master
          git checkout -t origin/master
          git checkout pull/1/merge
          git diff master...HEAD
         
      # - run: git ls-remote
      - name: Checkout head and target branch
        id: HeadandTarget
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          git fetch --no-tags --depth=1 origin ${{ github.head_ref }}
          # get the actual source for two branches
          git checkout origin/${{ github.base_ref }}
          git checkout origin/${{ github.head_ref }}
          # get back to the merge commit
          git checkout ${{ github.sha }}
          
          echo $TGT_PATH
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- $TGT_PATH )
            CHANGED_FILES_ARR=($CHANGED_FILES)
            echo "Processing ........."
