name: checkout

on: [pull_request]
jobs:
  AutoLabelandMerge:
    runs-on: ubuntu-latest
    env:
      TGT_PATH: 'aws/approle'  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
 
               
      # - run: git ls-remote
      - name: Checkout head and target branch
        id: HeadandTarget
        run: |
          git fetch --no-tags  origin ${{ github.base_ref }}
          git fetch --no-tags  origin ${{ github.head_ref }}
          # get the actual source for two branches
          git checkout origin/${{ github.base_ref }}
          git checkout origin/${{ github.head_ref }}
          # get back to the merge commit
          git checkout ${{ github.sha }}
          i=$(git merge-base remotes/origin/${{ github.base_ref }} remotes/origin/${{ github.head_ref }})
          
          echo "value of common commit base $i"
          
          echo $TGT_PATH
          
          git diff --name-only remotes/origin/${{ github.base_ref }}...remotes/origin/${{ github.head_ref }}

            CHANGED_FILES=$(git diff  $(git merge-base remotes/origin/${{ github.base_ref }} remotes/origin/${{ github.head_ref }}) origin/${{ github.head_ref }})
            CHANGED_FILES_ARR=($CHANGED_FILES)
            echo "updated"
            echo "Processing ........."
