name: checkout

on:
  pull_request:
    

  
    
jobs:
  AutoLabelandMerge:
    runs-on: ubuntu-latest
    env:
      TGT_PATH: 'aws/approle'  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
 
               
      # - run: git ls-remote
      - name: Checkout head and target branch
        id: HeadandTarget
        run: |
          echo sleeping for 100 s
          sleep 100
          
          
          echo " will run after other workflow" 
