name: checkout

on:
  
  workflow_run:  
     workflows: 
        - Github Auto PR Label,Approve and Merge
     types:
        - completed
 

  
    
jobs:
  AutoLabelandMerge:
    runs-on: ubuntu-latest
    env:
      TGT_PATH: 'aws/approle'  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
 
               
      # - run: git ls-remote
      - name: Checkout head and target branch
        id: HeadandTarget
        run: |
         echo " will run after other workflow" 
